# Generated by Django 3.2 on 2023-03-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_subject_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='epoch',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
