# Generated by Django 3.2 on 2023-03-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0033_comment_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_epoch',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
